### ISSUE TITLE
command `.update` is not correct

### ISSUE THREAD

**Issue by borpin** [openenergymonitor/emonpi#123]
https://github.com/openenergymonitor/emonpi/blob/master/firmware/compiled/readme.md

@glynhudson 

The line `.update` cannot be correct. as a minimum in needs a `cd` to move to the correct folder.

**Comment by glynhudson** [comment]
It's assuming the user is already in the emonpi folder. An explicit path was not mentioned sine the emonpi folder can be in different locations depending on the SD card build. I would say this is acceptable since this update script is only for developer use. Users should trigger update via the web interface.

**Comment by borpin** [comment]
@glynhudson  - it should be `./` not just `.`.

Assumptions are the mother of all &*^%ups and make an *ass* out of *u* and *me*.

Documentation should be clear, unambiguous and not make assumptions.
